const abl_array=["Cacophony",
"Speed Boost",
"Battle Armor",
"Sturdy",
"Damp",
"Static",
"Volt Absorb",
"Water Absorb",
"Oblivious",
"Insomnia",
"Color Change",
"Immunity",
"Own Tempo",
"Intimidate",
"Effect Spore",
"Natural Cure",
"Illuminate",
"Huge Power",
"Inner Focus",
"Soundproof",
"Pressure",
"Early Bird",
"Flame Body",
"Run Away",
"Pickup",
"Cute Charm",
"Guts",
"Overgrow",
"Rock Head",
"Vital Spirit",
"Pure Power",
"Tangled Feet",
"Motor Drive",
"Rivalry",
"Snow Cloak",
"Gluttony",
"Anger Point",
"Heatproof",
"Simple",
"Download",
"Iron Fist",
"Adaptability",
"Hydration",
"Quick Feet",
"Sniper",
"Super Luck",
"Anticipation",
"Unaware",
"Slow Start",
"Ice Body",
"Solid Rock",
"Honey Gather",
"Multitype",
"Flower Gift",
"Bad Dreams",
"Pickpocket",
"Sheer Force",
"Unnerve",
"Defiant",
"Defeatist",
"Cursed Body",
"Healer",
"Weak Armor",
"Heavy Metal",
"Toxic Boost",
"Harvest",
"Telepathy",
"Moody",
"Regenerator",
"Wonder Skin",
"Analytic",
"Illusion",
"Imposter",
"Mummy",
"Justified",
"Prankster",
"Zen Mode",
"Victory Star",
"Fur Coat",
"Bulletproof",
"Competitive",
"Strong Jaw",
"Desolate Land",
"Parental Bond",
"Dark Aura",
"Fairy Aura",
"Aura Break",
"Stamina",
"Wimp out",
"Stench",
"Scrappy",
"Klutz",
"Emergency Exit",
"Merciless",
"Berserk",
"Hustle",
"Disguise",
"Corrosion",
"Queenly Majesty",
"Innards Out",
"Dancer",
"Battery",
"Fluffy",
"Dazzling",
"Serene Grace",
"Tangling Hair",
"Receiver",
"Power of Alchemy",
"Beast Boost",
"Full Metal Body",
"Neuroforce",
"Intrepid Swod",
"Dauntless Shield",
"Ball Fetch",
"Gulp Missile",
"Sand Spit",
"Power Spot",
"Mimicry",
"Steely Spirit",
"Perish Body",
"Wandering Spirit",
"Gorilla Tactics",
"Hunger Switch",
"Quick Draw",
"Unseen Fist",
"Curious Medicine"];
output=abl_array[Math.floor(Math.random()*abl_array.length)]
