const products_array=["Dinosaur Egg",
                "Duck Egg",
                "Duck Feather",
                "Egg",
                "Goat Milk",
                "Golden Egg",
                "Large Egg",
                "Large Goat Milk",
                "Large Milk",
                "Milk",
                "Ostrich Egg",
                "Rabbit's Foot",
                "Roe",
                "Slime",
                "Slime Ball",
                "Truffle",
                "Void Egg",
                "Wool"];
output=products_array[Math.floor(Math.random()*products_array.length)]
