const artisan_array=["Honey",
                     "Wine",
                     "Pale Ale",
                     "Beer",
                     "Mead",
                     "Cheese",
                     "Goat Cheese",
                     "Coffe",
                     "Green Tea",
                     "Juice",
                     "Cloth",
                     "Mayonnaise",
                     "Truffle Oil",
                     "Oil",
                     "Pickles",
                     "Jelly",
                     "Caviar",
                     "Aged Roe"];
output=artisan_array[Math.floor(Math.random()*artisan_array.length)]
