const biome_array=["Badlands",
                   "Desert",
                   "Savanna",
                   "Stony Peaks",
                   "Jungle",
                   "Mushroom Fields",
                   "Plains",
                   "Swamp",
                   "Dripstone Caves",
                   "Dark Forest",
                   "Forest",
                   "Tall Birch Forest",
                   "Lush Caves",
                   "Birch Forest",
                   "River",
                   "Ocean",
                   "Warm Ocean",
                   "Cold Ocean",
                   "Meadows",
                   "Taiga",
                   "Mountains",
                   "Snowy Beach",
                   "Beach",
                   "Snowy Tundra",
                   "Frozen Ocean",
                   "Grove",
                   "Jagged Peaks",
                   "Frozen Peaks"];
output=biome_array[Math.floor(Math.random()*biome_array.length)]
