const castle_array=["Chrysalia, the bug type Castle",
                    "Yaksha, the dark type Castle",
                    "Dragnor, the dragon type Castle",
                    "Violight, the electric type Castle",     
                    "Fae, the new fairy type Castle",
                    "Pugilis, the fighting type Castle",
                    "Ignis, the fire type Castle",
                    "Avia, the flying type Castle",
                    "Spectra, the ghost type Castle",
                    "Greenleaf, the grass type Castle",
                    "Terrara, the ground type Castle",
                    "Nixtorm, the ice type Castle",
                    "Aurora, the normal type Castle",
                    "Viperia, the poison type Castle",    
                    "Illusio, the psychic type Castle",
                    "Cragspur, the rock type Castle",
                    "Valora, the steel type Castle",
                    "Fontaine, the water type Castle"];
output1=castle_array
