const class_array=["A-list Actor",
                   "Ace Trainer",
                   "Actor/Actress",
                   "Artist",
                   "Assistant",
                   "Athlete",
                   "Backpacker",
                   "Baker",
                   "Baron/Baroness",
                   "Battle Legend",
                   "Beauty",
                   "Beginning Trainer",
                   "Big Star",
                   "Biker",
                   "Bird Keeper",
                   "Black Belt",
                   "Bodybuilder",
                   "Brains & Brawn",
                   "Bug Catcher",
                   "Bug Maniac",
                   "Burglar",
                   "Butler",
                   "Café Master",
                   "Camper",
                   "Celebrity",
                   "Challenger",
                   "Channeler",
                   "Chef",
                   "Child Star",
                   "Clown",
                   "Collector",
                   "Comedian",
                   "Commander",
                   "Cook",
                   "Earl/Countess",
                   "Cute Trainer",
                   "Cyclist",
                   "Dancer",
                   "Delinquent",
                   "Doctor",
                   "Dragon Tamer",
                   "Duke/Duchess",
                   "Elite Four",
                   "Executive",
                   "Expert",
                   "Factory Head",
                   "Firebreather",
                   "Firefighter",
                   "Fisher",
                   "Gardener",
                   "Glitch Trainer",
                   "Golfer",
                   "Grand Duke/Duchess",
                   "Guitarist",
                   "Gym Challenger",
                   "Gym Leader",
                   "Gym Trainer",
                   "Hex Maniac",
                   "High-tech Maniac",
                   "Hiker",
                   "Honeymooner",
                   "Hunter",
                   "Idol",
                   "Interviewer",
                   "Island Kahuna",
                   "Janitor",
                   "Jogger",
                   "Juggler",
                   "Junior Representative",
                   "Kindler",
                   "Lass/Guy",
                   "Leader-in-Training",
                   "League Staff",
                   "Lone Wolf",
                   "Magician's Apprentice",
                   "Marquis/Marchioness",
                   "Master Dojo Student",
                   "Master Representative",
                   "Medium",
                   "Model",
                   "Movie Star",
                   "Music Crew",
                   "Musician",
                   "Myth Trainer",
                   "Navigator",
                   "New Star",
                   "Newscaster",
                   "Novice",
                   "Nurse",
                   "Office Worker",
                   "Ordinary Guy/Lady",
                   "Painter",
                   "Passionate Rider",
                   "Picnicker",
                   "Pikachu Fan",
                   "Pilot",
                   "Poké Fan",
                   "Poké Kid",
                   "Pokémon Breeder",
                   "Pokémon Champion",
                   "Pokémon Ranger",
                   "Police Officer",
                   "Preschooler",
                   "Principal",
                   "Psychic",
                   "Rail Staff",
                   "Rancher",
                   "Reporter",
                   "Rider",
                   "Rising Star",
                   "Rival",
                   "Rocker",
                   "Roller Skater",
                   "Rookie",
                   "Ruin Maniac",
                   "Sage",
                   "Sailor",
                   "Schoolkid",
                   "Sci-Fi Maniac",
                   "Scientist",
                   "Scuba Diver",
                   "Secret Base Trainer",
                   "Senior Representative",
                   "Sightseer",
                   "Skier",
                   "Sky Trainer",
                   "Smasher",
                   "Sprout Trainer",
                   "Spy",
                   "Striker",
                   "Super Nerd",
                   "Surfer",
                   "Swimmer",
                   "Tamer",
                   "Teacher",
                   "Team Aqua Grunt",
                   "Team Flare Grunt",
                   "Team Magma Grunt",
                   "Team Plasma Grunt",
                   "Tem Rocket Grunt",
                   "Team Skull Grunt",
                   "Team Yell Grunt",
                   "Tourist",
                   "Trial Captain",
                   "Triathlete",
                   "Tuber",
                   "Veteran",
                   "Warden",
                   "Warlord",
                   "Warrior",
                   "Worker",
                   "Youngster",
                   "Youth Athlete"];
output=class_array[Math.floor(Math.random()*class_array.length)]
