const crops_array=["Blue Jazz",
                  "Cauliflower",
                  "Coffee Bean",
                  "Garlic",
                  "Green Bean",
                  "Kale",
                  "Parsnip",
                  "Potato",
                  "Rhubarb",
                  "Strawberry",
                  "Tulip",
                  "Unmilled Rice",
                  "Blueberry",
                  "Corn",
                  "Hops",
                  "Hot Pepper",
                  "Melon",
                  "Poppy",
                  "Radish",
                  "Red Cabbage",
                  "Starfruit",
                  "Summer Sprangle",
                  "Sunflower",
                  "Tomato",
                  "Wheat",
                  "Amaranth",
                  "Artichoke",
                  "Beet",
                  "Bok Choy",
                  "Cranberries",
                  "Eggplant",
                  "Fairy Rose",
                  "Grape",
                  "Pumpkin",
                  "Yam"];
output=crops_array[Math.floor(Math.random()*crops_array.length)]
