const dnd_array=[["Dragonborn",
                   "Dwarf",
                   "Elf",
                   "Gnome",
                   "Half-Elf",
                   "Halfling",
                   "Half-Orc",
                   "Human",
                   "Tiefling",
                   "Aarakocra",
                   "Aasimar",
                   "Air Genasi",
                   "Bugbear",
                   "Centaur",
                   "Changeling",
                   "Deep Gnome",
                   "Duergar",
                   "Earth Genasi",
                   "Eladrin",
                   "Fairy",
                   "Firbolg",
                   "Fire Genasi",
                   "Githyanki",
                   "Githzerai",
                   "Goblin",
                   "Goliath",
                   "Harengon",
                   "Hobgoblin",
                   "Kenku",
                   "Kobold",
                   "Lizardfolk",
                   "Minotaur",
                   "Orc",
                   "Satyr",
                   "Sea Elf",
                   "Shadar-kai",
                   "Shifter",
                   "Tabaxi",
                   "Tortle",
                   "Triton",
                   "Water Genasi",
                   "Yuan-ti",
                   "Kender",
                   "Astral Elf",
                   "Autognome",
                   "Giff",
                   "Hadozee",
                   "Plasmoid",
                   "Thri-kreen",
                   "Owlin",
                   "Leonin",
                   "Warforged",
                   "Verdan",
                   "Loxodon",
                   "Simic Hybrid",
                   "Vedalken",
                   "Feral Tiefling",
                   "Locathah",
                   "Grung"],
                  ["Barbarian",
                   "Bard",
                   "Cleric",
                   "Druid",
                   "Fighter",
                   "Monk",
                   "Paladin",
                   "Ranger",
                   "Rogue",
                   "Sorcerer",
                   "Warlock",
                   "Wizard",
                   "Artificer",
                   "Blood Hunter"],
                 ["Acrobatics",
                  "Animal Handling",
                  "Arcana",
                  "Athletics",
                  "Deception",
                  "History",
                  "Insight",
                  "Intimidation",
                  "Investigation",
                  "Medicine",
                  "Nature",
                  "Perception",
                  "Performance",
                  "Persuasion",
                  "Religion",
                  "Sleight of Hand",
                  "Stealth",
                  "Survival"]];
op=dnd_array
