const mods_array=["Kat",
                  "Dani",
                  "Rach",
                  "Cav",
                  "Ella",
                  "Kay",
                  "Sam",
                  "Cbiii",
                  "Nightbot",
                  "Camden himself, but he lost control over mod actions",
                  "The one who simps for maps",
                  "The one who loves gardening",
                  "The one addicted to dueling on Bryce's",
                  "The one who is roasted by bots",
                  "The one who likes Haley",
                  "The one who has a blackbelt",
                  "The one who loves sports",
                  "The one who likes math",
                  "The Canadian one",
                  "The one who has 11 pillows",
                  "The one who roasts italian",
                  "The one addicted to Pokemon Unite",
                  "The one who does a lot of typos",
                  "Very confused with stuff Kay posts in ModChat",
                  "Actually a bot",
                  "The one who can't see colors",
                  "The cute one (all of them)",
                  "The one who's saving for next no transposing redemption",
                  "Actually Bryce disguised",
                  "The one who hates bots",
                  "The one who went to school in a forest",
                  "samjPerry",
                  "The one with the rolex story",
                  "The kiddo",
                  "The one who misses Mod Farm",
                  "The one who got infuriated with Camden's takes on the pokemon fist-fight tierlist",
                  "The one who banned a lot of bots in their first day",
                  "Timing out italian in another chat",
                  "Dani's wife",
                  "Rach's wife",
                  "The one with a funny discord name"];
output=mods_array[Math.floor(Math.random()*mods_array.length)]
