const moon_array=["Slipping Through the Poison Tide",
                  "The Forgotten Treasure",
                  "Under the Big One's Brim",
                  "Roll On and On",
                  "Precision Rolling",
                  "Chomp Through the Rocks",
                  "Good Morning, Captain Toad!",
                  "Caveman Cave-Fan",
                  "Just a Hat, Skip, and a Jump",
                  "Treasure Under the Cliff",
                  "Guarded by a Colossal Fossil",
                  "Across the Mysterious Clouds",
                  "Showdown on the Inverted Pyramid",
                  "The Hole in the Desert",
                  "Alcove in the Ruins",
                  "Secret of the Mural",
                  "Where the Birds Gather"];
output=moon_array[Math.floor(Math.random()*moon_array.length)]
