const moon_array=["Slipping Through the Poison Tide",
                  "The Forgotten Treasure",
                  "Under the Big One's Brim",
                  "Roll On and On",
                  "Precision Rolling",
                  "Chomp Through the Rocks",
                  "Good Morning, Captain Toad!",
                  "Caveman Cave-Fan",
                  "Just a Hat, Skip, and a Jump",
                  "Treasure Under the Cliff",
                  "Guarded by a Colossal Fossil",
                  "Across the Mysterious Clouds",
                  "Showdown on the Inverted Pyramid",
                  "The Hole in the Desert",
                  "Alcove in the Ruins",
                  "Secret of the Mural",
                  "Where the Birds Gather",
                  "Lost in the Luggage",
                  "Inside a Block Is a Hard Place",
                  "The Lurker Under the Stone",
                  "Love in the Heart of the Desert",
                  "You're Quite a Catch, Captain Toad!",
                  "Sand Quiz: Wonderful!",
                  "Employees Only",
                  "Under the Mummy's Curse",
                  "Dancing with New Friends",
                  "Strange Neighborhood",
                  "Our Secret Little Room",
                  "What's in the Box?",
                  "I Feel Underdressed",
                  "Super-Secret Zipper",
                  "Jump, Grab, Cling, and Climb",
                  "That Trendy 'Pirate' Look",
                  "Space Is 'In' Right Now",
                  "That 'Old West' Style",
                  "Deep, Deep Down",
                  "Love by the Lake",
                  "Waves of Poison: Hoppin' Over",
                  "Waves of Poison: Hop to It!",
                  "Caught Hopping in the Forest!",
                  "Thanks for the Charge!",
                  "Atop the Tall Tree",
                  "The Nut at the Dead End",
                  "Cracked Nut on a Crumbling Tower",
                  "Love in the Forest Ruins",
                  "Stretching Your Legs",
                  "Past the Peculiar Pipes",
                  "By the Babbling Brook in Deep Woods",
                  "A Treasure Made from Coins",
                  "Deep Woods Treasure Trap",
                  "Nut Hidden in the Fog"];
output=moon_array[Math.floor(Math.random()*moon_array.length)]
