const moon_array=["Slipping Through the Poison Tide",
                  "The Forgotten Treasure",
                  "Under the Big One's Brim",
                  "Roll On and On",
                  "Precision Rolling",
                  "Chomp Through the Rocks",
                  "Good Morning, Captain Toad!",
                  "Caveman Cave-Fan",
                  "Just a Hat, Skip, and a Jump",
                  "Treasure Under the Cliff",
                  "Guarded by a Colossal Fossil",
                  "Across the Mysterious Clouds",
                  "Showdown on the Inverted Pyramid",
                  "The Hole in the Desert",
                  "Alcove in the Ruins",
                  "Secret of the Mural",
                  "Where the Birds Gather",
                  "Lost in the Luggage",
                  "Inside a Block Is a Hard Place",
                  "The Lurker Under the Stone",
                  "Love in the Heart of the Desert",
                  "You're Quite a Catch, Captain Toad!",
                  "Sand Quiz: Wonderful!",
                  "Employees Only",
                  "Under the Mummy's Curse",
                  "Dancing with New Friends",
                  "Strange Neighborhood",
                  "Our Secret Little Room",
                  "What's in the Box?",
                  "I Feel Underdressed",
                  "Super-Secret Zipper",
                  "Jump, Grab, Cling, and Climb",
                  "That Trendy 'Pirate' Look",
                  "Space Is 'In' Right Now",
                  "That 'Old West' Style",
                  "Deep, Deep Down",
                  "Love by the Lake",
                  "Waves of Poison: Hoppin' Over",
                  "Waves of Poison: Hop to It!",
                  "Caught Hopping in the Forest!",
                  "Thanks for the Charge!",
                  "Atop the Tall Tree",
                  "The Nut at the Dead End",
                  "Cracked Nut on a Crumbling Tower",
                  "Love in the Forest Ruins",
                  "Stretching Your Legs",
                  "Past the Peculiar Pipes",
                  "By the Babbling Brook in Deep Woods",
                  "A Treasure Made from Coins",
                  "Deep Woods Treasure Trap",
                  "Nut Hidden in the Fog",
                  "Hot, Hot, Hot from the Campfire",
                  "Invisible Road: Danger!",
                  "Picture Match: Basically a Goomba",
                  "Picture Match: A Stellar Goomba!",
                  "Inside the Stone Cage",
                  "Wrecked Rock Block",
                  "Twist 'n' Turn-Up Treasure"
                  "The Caged Gold",
                  "Get Some Rest, Captain Toad",
                  "Taxi Flying Through Forgotten Isle",
                  "I Met a Tropical Wiggler!",
                  "Extremely Hot Bath	",
                  "New Donk City's Pest Problem",
                  "A Traditional Festival!",
                  "Glittering Above the Pool",
                  "Who Piled Garbage on This?",
                  "Bench Friends",
                  "High Over the Crowd",
                  "One Man's Trash...	",
                  "A Tourist in the Metro Kingdom!",
                  "Surprise Clown!",
                  "Up on the Big Screen",
                  "Found in the Park! Good Dog!",
                  "Caught Hopping in the Snow!",
                  "Walking on Ice!",
                  "Shining on High",
                  "Forgotten in the Holding Room",
                  "On the Cliff Overlooking the Beach",
                  "Wriggling on the Sandy Bottom"];
output=moon_array[Math.floor(Math.random()*moon_array.length)]
