const motto_array=["Alienate, Aggravate, Assert",
                  "Bed, Bath, and Beyond",
                  "Catcall, Catcreep, Catalogue",
                  "Diners, Drive-Thrus, and Dives",
                  "Expunge, Extricate, Explain",
                  "Flake, fake, fabricate",
                  "hero, himbo,wHore",
                  "Isolate, Ignore, ibuprofen",
                  "Juke, Jebait, Justify",
                  "Kiss, Kick, Kill",
                  "Live, Laugh, Love",
                  "Manipulate, Mansplain, Make up",
                  "Outwit, Outplay, Outlast",
                  "Plagiarize, Popularize, Profit",
                  "Queer, Quote, Queen",
                  "Reduce, Reuse, Recycle",
                  "Slay, Serve, Survive",
                  "Transpose, Transcend, Transgender",
                  "Ungovernable, Unmarketable, Unapologetic",
                  "Veni, Vidi, Vici",
                  "Weep, Whine, Weaponize",
                  "Yikes, Yoink, Yeet",
                  "Zen, Zine, Zuck",
                  "Stop, Drop, Roll",
                  "Improvise, Adapt, Overcome",
                  "Imagine, Believe, Achieve",
                  "Ready, Aim, Fire",
                  "Lights, Camera, Action",
                  "Ready, Set, Go!"];
output=motto_array[Math.floor(Math.random()*motto_array.length)]
