const move_array=["After You",
                 "Assist",
                 "Attract",
                 "Belly Drum",
                 "Block",
                 "Body Slam",
                 "Celebrate",
                 "Confide",
                 "Covet",
                 "Defense Curl",
                 "Double Slap",
                 "Echoed Voice",
                 "Encore",
                 "Endure",
                 "Entrainment",
                 "Facade",
                 "Focus Energy",
                 "Follow me",
                 "Frustration",
                 "Glare",
                 "Happy Hour",
                 "Headbutt",
                 "Helping Hand",
                 "Hold Hands peepoShy",
                 "Judgement",
                 "Leer",
                 "Lovely Kiss",
                 "Mean Look",
                 "Milk Drink",
                 "Mimic",
                 "Pay Day abbybaCash",
                 "Perish Song",
                 "Pound",
                 "Play Nice",
                 "Rage",
                 "Recycle",
                 "Round",
                 "Scary Face",
                 "Scratch",
                 "Sing",
                 "Sketch",
                 "Slack Off",
                 "Sleep Talk",
                 "Splash",
                 "Stomp",
                 "Struggle",
                 "Swagger",
                 "Sweet Scent",
                 "Tackle",
                 "Tearfull Look",
                 "Teatime",
                 "Thrash",
                 "Tickle",
                 "Wish",
                 "Work Up",
                 "Yawn",
                 "Close Combat",
                 "Counter",
                 "Double Kick",
                 "Final Gambit",
                 "Focus Punch",
                 "Low Kick",
                 "Revenge",
                 "Wake-Up Slap",
                 "Chatter",
                 "Gastro Acid",
                 "Mud Slap",
                 "Sand Attack",
                 "Rock Throw",
                 "First Impression",
                 "Astonish",
                 "Curse",
                 "Lick BLELELE",
                 "Spite",
                 "Trick-or-Treat",
                 "Burning Jealousy",
                 "Dive",
                 "Soak",
                 "Withdraw",
                 "Amnesia",
                 "Calm Mind",
                 "Confusion",
                 "Meditate",
                 "Rest",
                 "Role Play",
                 "Assurance",
                 "Bite abbybaNom",
                 "Crunch",
                 "Fake Tears",
                 "Flatter",
                 "Nasty Plot",
                 "Punishment",
                 "Taunt",
                 "Baby-Doll Eyes",
                 "Charm",
                 "Disarming Voice",
                 "Play Rough",
                 "Sweet Kiss"];
output=move_array[Math.floor(Math.random()*move_array.length)]
