const kay_array=["looking for flags on etsy",
                 "talking about math to an uninterested listener",
                 "preaching about railroads",
                 "reading some book even him doesn't understand",
                 "playing Pokemon as usual",
                 "googling the population of some obscure city",
                 "drawing Pokemon stuff",
                 "watching football",
                 "screaming at plants or something",
                 "washing his hair",
                 "knocking at your door (just kidding he can't pay for plane tickets)",
                 "talking about flags",
                 "working on some math stuff",
                 "making food and overestimating his level of creativity",
                 "writing some TTRPG campaign he will either forget about or give up on",
                 "laughing alone at map memes",
                 "laughing alone at flag memes",
                 "writing another command. It happens",
                 "teaching math to uninitiated",
                 "sleeping"
                 ];
output=kay_array[Math.floor(Math.random()*mods_array.length)]
