const cities_array=["Pallet Town",
                   "Viridian City",
                   "Pewter City",
                   "Cerulean City",
                   "Vermilion City",
                   "Lavender Town",
                   "Celadon City",
                   "Fuchsia City",
                   "Saffron City",
                   "Cinnabar Island",
                   "New Bark Town",
                   "Cherrygrove City",
                   "Violet City",
                   "Azalea Town",
                   "Goldenrod City",
                   "Ecruteak City",
                   "Olivine City",
                   "Cianwood City",
                   "Mahogany Town",
                   "Blackhorn City",
                   "Littleroot Town",
                   "Oldale Town",
                   "Petalburg City",
                   "Rustboro City",
                   "Dewford Town",
                   "Slateport City",
                   "Mauville City",
                   "Verdanturf Town",
                   "Fallabor Town",
                   "Lavaridge Town",
                   "Fortree City",
                   "Lilycove City",
                   "Mossdeep City",
                   "Sootopolis City",
                   "Pacifidlog Town",
                   "Twinleaf Town",
                   "Sandgem Town",
                   "Jubilife City",
                   "Oreburgh City",
                   "Floraroma Town",
                   "Eterna City",
                   "Hearthome City",
                   "Solaceon Town",
                   "Veilstone City",
                   "Pastoria City",
                   "Celestic Town",
                   "Canalave City",
                   "Snowpoint City",
                   "Sunyshore City",
                   "Nuvema Town",
                   "Accumula Town",
                   "Striaton City",
                   "Nacrene City",
                   "Castelia City",
                   "Nimbasa City",
                   "Driftveil City",
                   "Mistralton City",
                   "Icirrus City",
                   "Opelucid City",
                   "Vaniville Town",
                    "Aquacorde Town",
                    "Santalune City",
                    "Lumiose City",
                    "Camphrier Town",
                    "Cyllage City",
                    "Ambrette Town",
                    "Geosenge Town",
                    "Shalour City",
                    "Coumarine City",
                    "Laverre City",
                    "Dendemille Town",
                    "Anistar City",
                    "Couriway Town",
                    "Snowbelle City",
                    "Iki Town",
                    "Hau'oli City",
                    "Heahea City",
                    "Paniola Town",
                    "Konikoni City",
                    "Malie City",
                    "Tapu Village",
                    "Po Town",
                    "Seafolk Village",
                    "Postwick",
                    "Wedgehurst",
                    "Motostoke",
                    "Turffield",
                    "Hulbury",
                    "Hammerlocke"
                    "Stow-on-Side",
                    "Ballonlea",
                    "Circhester",
                    "Spikemuth",
                    "Wyndon"
                   ];
output=cities_array[Math.floor(Math.random()*cities_array.length)]
