const smells_array=["Perfume",
                     "Flowers",
                     "Fresh Cut Grass",
                     "A new book",
                     "A fruit basket",
                     "Vanilla",
                     "Mint",
                     "Eucalyptus",
                     "Lavender",
                     "Pop Corn",
                     "Cookies Fresh out of the Oven",
                     "Melting Chocolate",
                     "Rain over a grassy Field",
                     "Wales"
                     "Bacon",
                     "Clothes Fresh out of the Drier",
                     "Wet Dog",
                     "Chocolate",
                     "Babies after bath",
                     "Babies before bath",
                     "Emily's goat that the other goat peed upon",
                     "Baking Bread",
                     "Fish",
                     "Toxic Waste",
                     "Sewers",
                     "Dirty Socks",
                     "Eggs",
                     "Gasoline",
                     "Puppy Breath",
                     "Skunks",
                     "Bus Exhaust",
                     "Livestock",
                     "Burnt Rubber",
                     "Burnt Toast",
                     "A bag of cheetos",
                     "Sour Milk",
                     "Cigar Smoke"];
output=smells_array[Math.floor(Math.random()*smells_array.length)]
