const tabs_array=["Ancient Tank",
                 "Archer",
                 "Ball'n'Chain",
                 "Ballista",
                 "Balloon Archer",
                 "Ballooner",
                 "Bank Robbers",
                 "Banner Bearer",
                 "Banshee",
                 "Barbarian",
                 "Bard",
                 "Barrel Roller",
                 "Beamer",
                 "Berserker",
                 "Blackbeard",
                 "Blue",
                 "Bomb Cannon",
                 "Bomb on a Stick",
                 "Bomb Thrower",
                 "Bone Mage",
                 "Brawler",
                 "Cactus",
                 "Cannon",
                 "Captain",
                 "Catapult",
                 "Cavalry",
                 "Centaur",
                 "Cheerleader",
                 "Chicken Man",
                 "Chicken Man Man",
                 "Chronomancer",
                 "Cupid",
                 "Da Vinci Tank",
                 "Dragon",
                 "Dynamite Thrower",
                 "Energy Sword Master",
                 "Fan Bearer",
                 "Farmer",
                 "Fire Archer",
                 "Flamethrower",
                 "Flag Bearer",
                 "Gattling Gun",
                 "Gravity Dude",
                 "Greek Philosopher",
                 "Headbutter",
                 "Halfling",
                 "Healer",
                 "Harvester",
                 "Ice Giant",
                 "Ice Mage",
                 "Jester",
                 "Knight",
                 "Mad Mechanic",
                 "Mammoth",
                 "Minotaur",
                 "Monk",
                 "Necromancer",
                 "Ninja",
                 "Painter",
                 "Pharaoh",
                 "Pirate Queen",
                 "Potionseller",
                 "Present Elf",
                 "Red",
                 "Raptor",
                 "Scarecrow",
                 "Shadow Walker",
                 "Skeleton Giant",
                 "Snake Archer",
                 "Spear Thrower",
                 "Stoner",
                 "Super Peasant",
                 "Tank",
                 "Tesla",
                 "The King",
                 "The Teacher",
                 "Thor",
                 "Valkyrie",
                 "Vampire",
                 "Witch",
                 "Wizard",
                 "Zeus"];
output=tabs_array[Math.floor(Math.random()*tabs_array.length)]
