const tie_array=[" Floral ",
                 " Bee ",
                 " Twitch dog's bow",
                 " Duck ",
                 " Flags ",
                 " Piano ",
                 " Popsicles ",
                 " Chimken ",
                 " Stripey ",
                 " Polka-dot ",
                 " Novelty ",
                 " Plaid ",
                 " Paisley ",
                 " Geometric ",
                 " Motif ",
                 "n Abstract ",
                 " New and curious type of ",
                 "n Elegant but vibrant ",
                 " solid and serene ",
                 " Team Teal ",
                 " Purple Squad ",
                 "n Orange Gang ",
                 " Booba9 Club ",
                 " Gold Crew ",
                 " Pink Party ",
                 " Green Band ",
                 " Blue Bunch ",
                 " Red Company ",
                 " Plain White ",
                 " Glowing sticks ",
                 " Peek at the next great ",
                 " Legendary 31st ",
                 " Futuristic and full of mirrors ",
                 " Classic ",
                 " Britney ",
                 " Cars 2 Merch ",
                 " Romantic Events ", 
                 " Flirty ",
                 " Memey ",
                 " Kirby Merch ",
                 " Smant Merch ",
                 " Beat up but still nice looking lucky",
                 " Second brand Duck ",
                 " Nicely tied ",
                 " Very poorly tied ",
                 " Not tied, kind of laying on the shoulders ",
                 "n Unique and very valid ",
                 " 400 dollars " ];
output=tie_array[Math.floor(Math.random()*tie_array.length)]
