const tie_array=[" Floral ",
                 " Bee ",
                 " Twitch dog's bow",
                 " Duck ",
                 " Flags ",
                 " Piano ",
                 " Popsicles ",
                 " Chimken ",
                 " Stripey ",
                 " Polka-dot ",
                 " Novelty ",
                 " Plaid ",
                 " Paisley ",
                 " Geometric ",
                 " Motif ",
                 "n Abstract ",
                 " New and curious type of ",
                 "n Elegant but vibrant ",
                 " solid and serene ",
                 " Team Teal ",
                 " Purple ",
                 "n Orange ",
                 " Booba9 Club ",
                 " Plain White ",
                 " Glowing sticks ",
                 " Peek at the next great ",
                 " Legendary 35th ",
                 " Futuristic and full of mirrors ",
                 " Classic ",
                 " Britney ",
                 " Cars 2 Merch ",
                 " Romantic Events ", 
                 " Flirty ",
                 " Memey ",
                 " Kirby Merch ",
                 " Smant Merch ",
                 " Beat up but still nice looking lucky",
                 " Second brand Duck ",
                 " Nicely tied ",
                 " Very poorly tied ",
                 " not tied, kind of laying on the shoulders ",
                 "n Unique and very valid ",
                 " 400 dollars ",
                 " Painting ",
                 " Dinosaur ",
                 "n Arcade ",
                 " Llama slash Alpaca ",
                 " Sharks ",
                 " Cat Instrument ",
                 "n Otters ",
                 " Flamingo ",
                 " Lego ",
                 " Noodles",
                 " Bacon ",
                 " Corn ",
                 " Dentistry ",
                 " Canada & US flags ",
                 " Fries ",
                 " B R A Z I L ",
                 " Purple Floral ",
                 " Turtles ",
                 " Train ",
                 " Sloth ",
                 " Blue Sky - A painting from Vincent Bus Stohp that is legally NOT Starry Night - ",
                 " Mustache Train ",
                 " Lesbian-Pansexual ",
                 " FISH FEAR ME ",
                 " Overly Expensive Pokémon ",
                 " Fish ",
                 " microphone "];
output=tie_array[Math.floor(Math.random()*tie_array.length)]
