const totk_array=[["Chuchu",
                   "Fire Chuchu",
                   "Ice Chuchu",
                   "Electric Chuchu",
                   "Bokoblin",
                   "Blue Bokoblin",
                   "Black Bokoblin",
                   "Silver Bokoblin",
                   "Stalkoblin",
                   "Boss Bokoblin",
                   "Blue Boss Bokoblin",
                   "Black Boss Bokoblin",
                   "Silver Boss Bokoblin",
                   "Soldier Construct I",
                   "Soldier Construct II",
                   "Soldier Construct III",
                   "Soldier Construct IV",
                   "Captain Construct I",
                   "Captain Construct II",
                   "Captain Construct III",
                   "Captain Construct IV",
                   "Gibdo",
                   "Moth Gibdo",
                   "Horriblin",
                   "Blue Horriblin",
                   "Black Horriblin",
                   "Silver Horriblin",
                   "Keese",
                   "Electric Keese",
                   "Fire Keese",
                   "Ice Keese",
                   "Keese Swarm",
                   "Lizalfos",
                   "Blue Lizalfos",
                   "Black Lizalfos",
                   "Silver Lizalfos",
                   "Stalizalfos",
                   "Lynel",
                   "White-Manned Lynel",
                   "Blue-Manned Lynel",
                   "Silver Lynel",
                   "Moblin",
                   "Blue Moblin",
                   "Black Moblin",
                   "Silver Moblin",
                   "Stalmoblin",
                   "Water Octorock",
                   "Forest Octorock",
                   "Rock Octorock",
                   "Treasure Octorock",
                   "Fire Wizzrobe",
                   "Meteo Wizzrobe",
                   "Frost Wizzrobe",
                   "Blizzrobe",
                   "Electric Wizzrobe",
                   "Thunder Wizzrobe",
                   "Yiga Footsoldier",
                   "Yiga Blademaster",
                   "Stone Pebblit",
                   "Frost Pebblit",
                   "Igneo Pebblit",
                   "Like Like",
                   "Fire Like",
                   "Ice Like",
                   "Shock Like",
                   "Rock Like",
                   "Little Frox",
                   "Evermean",
                   "Aerocuda",
                   "Gloom Spawn",
                   "Stone Talus",
                   "Battle Talus",
                   "Igneo Talus",
                   "Frost Talus",
                   "Hinox",
                   "Blue Hinox",
                   "Black Hinox",
                   "Silver Hinox",
                   "Molduga",
                   "Flame Gleeok",
                   "Frost Gleeok",
                   "Thunder Gleeok",
                   "King Gleeok"],
  ["Royal Guard's Claymore",
   "Boulder Breaker",
   "Fierce Deity Sword",
   "Royal Claymore",
   "Bigooron's Sword",
   "Gloom Club",
   "Royal Guard's Sword",
   "Gloom Sword",
   "Gloom Spear",
   "Knight's Claymore",
   "Royal Broadsword",
   "Scimitar of the Seven",
   "Eightfold Longblade",
   "Royal Guard's Spear",
   "Dusk Claymore",
   "master Sword",
   "Knight's Broadsword",
   "Royal Halberd",
   "Giant Boomerang",
   "White Sword of the Sky",
   "Forest Dweller's Sword",
   "Lightscale Trident",
   "Sea-Breeze Boomerang",
   "Soldier's Claymore",
   "Gnarled Thick Stick",
   "Sword Of Hero",
   "Gerudo Scimitar",
   "Farming Hoe",
   "Gerudo Spear",
   "Eightfold Blade",
   "Zora Sword",
   "Cobble Crusher",
   "Feathered Edge",
   "Moblin Arm",
   "Mighty Zonaite Longsword",
   "Lizal Boomerang",
   "Soldier's Broadsword",
   "Boat Oar",
   "Gnarled Wooden Stick",
   "Knight's Halberd",
   "Lizalfos Arm",
   "Rusty Claymore",
   "Forest Dweller's Spear",
   "Traveler's Claymore",
   "Strong Zonaite Longsword",
   "Mighty Zonaite Sword",
   "Gerudo Claymore",
   "Gnarled Long Stick",
   "Zonaite Sword",
   "Boomerang",
   "Fishing Harpoon",
   "Zora Longsword",
   "Zonaite Longsword",
   "Mighty Zonaite Spear",
   "Soldier's Spear",
   "Zonaite Spear",
   "Strong Zonaite Sword",
   "Sturdy Thick Stick",
   "Magic Scepter",
   "Rusty Broadsword",
   "Throwing Spear",
   "Zora Spear",
   "Magic Rod",
   "Rusty-Claymore",
   "Strong Zonaite Spear",
   "Bokoblin Arm",
   "Traveler's Sword",
   "Rusty Halberd",
   "Wooden Mop",
   "Sturdy Wooden Stick",
   "Thick Stick",
   "Soup Ladle",
   "Feathered Spear",
   "Wooden Stick",
   "Sturdy Long Stick",
   "Magic Staff",
   "Traveler's Spear",
   "Torch",
   "Tree Branch",
   "Farmer's Pitchfork",
   "Long Stick",
   "Decayed Master Sword"]];
op=totk_array
